Feat/felice
lenyeg/linktree-paranavai.app pull request #6
Opened 2022-12-21 16:24 UTC by lukinhas711

Como requisitado pelo André movi o linktree da Felice para este repositório, atualizei algumas dependencias e fiz mais algumas alterações no package.json. ^^

2023-01-04 15:20 UTC, andrevandal requested changes
solicitei alterações via Jira

https://lenyeg.atlassian.net/browse/CORE-153

2023-01-04 17:36 UTC, lukinhas711 commented
> solicitei alterações via Jira
> 
> https://lenyeg.atlassian.net/browse/CORE-153

Fiz as alterações vizuais, subi sem ter completado tudo pra poder testar o banner social pela url de preview

2023-01-04 17:46 UTC, lukinhas711 commented
@andrevandal eu alterei a versão do node como me prdiu(no package e no nvmrc) porem no CF ele continua usando a versão 16 porque esta lendo a 16 no nvmrc, não encontrei se tem algum cach para ser limpo.
![image](https://user-images.githubusercontent.com/49355209/210617259-cd5a74df-4a5d-46df-a5f5-77d239822c16.png)

2023-01-04 17:53 UTC, lukinhas711 commented
O node 18 não esta buildando
![image](https://user-images.githubusercontent.com/49355209/210618590-fb60346b-4e47-48b6-adc9-978ac140c747.png)

Encontrei isso, e no stackoverflow eles falam pra usar o 16 tambem... 
![image](https://user-images.githubusercontent.com/49355209/210618460-636b8f7e-43a2-49ce-97ee-8a94dff641de.png)

2023-01-04 17:54 UTC, lukinhas711 commented
Vou usar o 16 para testar o banner

2023-01-12 17:02 UTC, andrevandal approved these changes
mandou muito bem!

gostei que testou a versão, viu que não deu certo e eu estava errado, achou o motivo que embasa o que decidiu e compartilhou comigo para aprendermos juntos!

o único improvement para a próxima é por o link do stackoverflow para no futuro sabermos se alguém respondeu lá com boas noticiias.

2023-01-12 17:55 UTC, merged